name: DEPLOY-EC2

on:
  push:
    branch:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Build Docker Image
        run: docker build -t rokondoc/react-test .
      - name: Publish image to docker hub
        run: docker push rokondoc/react-test:latest

  deploy:
    needs: build
    runs-on: react-test
    steps:
      - name: Pull image from docker hub
        run: docker pull rokondoc/react-test:latest
      - name: Delete Old Container
        run: docker rm -f reactContainer || true
      - name: Run docker container
        run: docker run -d -p 3000:80 --name reactContainer rokondoc/react-test:latest